version: '3'
services:
  cmy:
    container_name: cmy
    image: cmy:latest
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./config:/app/config
    environment:
      - TZ=America/Caracas
      - CLOUD_PROVIDER=LOCAL
      - SHOW_DIR=true
      - DOCKER_TIMEZONE=America/Caracas
      - SEND_NOTIFICATIONS=true